
on:
  - push
  - pull_request
  - workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  add-tag:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git tag -f -a now -m "Tag created $(date -u -I seconds)"
        git push --force origin now
      env:
        GITHUB_TOKEN: ${{ github.token }}
