
on:
  - push
  - pull_request
  - workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  add-tag:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - run: git tag -f -a now -m "Tag created $(date -u -I seconds)"
      env:
        GITHUB_TOKEN: ${{ github.token }}
