# Adapted from: https://github.com/actions/cache/issues/342#issuecomment-1363953531

on:
  - push
  - pull_request
  - workflow_dispatch

defaults:
  run:
    shell: bash

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  cache-test:
    runs-on: ubuntu-latest
    steps:

    - name: Restore cache
      id: cache-restore
      uses: actions/cache/restore@v3
      with:
        path: date.txt
        key: the-key

    - name: Old date
      if:   ${{ steps.cache-restore.outputs.cache-hit }}
      run:  cat date.txt

    # Checkout is needed for using gh
    # Need to do this before writing any new files, as checkout deletes everything
    - name: Checkout the repo
      uses: actions/checkout@v3
      if:   ${{ steps.cache-restore.outputs.cache-hit }}

    - name: Save the date
      run:  |
        date
        date > date.txt

    - name: Clear the cache
      if:   ${{ steps.cache-restore.outputs.cache-hit }}
      run: |
        gh extension install actions/gh-actions-cache
        gh actions-cache delete the-key --confirm

    - name: Save the cache
      uses: actions/cache/save@v3
      # if: always()  # save cache even fails
      with:
        path: date.txt
        key:  the-key
