# Adapted from: https://github.com/actions/cache/issues/342#issuecomment-1363953531

on:
  - push
  - pull_request
  - workflow_dispatch

defaults:
  run:
    shell: bash

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  cache-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        # [ubuntu-latest,windows-latest]

    env:
      key: ${{ matrix.os }}
      msys2-path: '/c/msys64/mingw64/bin:/c/msys64/usr/bin'

    steps:

    - name: Set up MSYS2 PATH (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: |
        PATH="${PATH};${{ env.msys2-path }}"
        which pacman
        which pkg-config
        echo "${{ env.msys2-path }}" >> "${GITHUB_PATH}"

    - name: Restore cache
      id: cache-restore
      uses: actions/cache/restore@v3
      with:
        path: date.txt
        key: ${{ env.key }}

    - name: Old date
      if:   ${{ steps.cache-restore.outputs.cache-hit }}
      run:  cat date.txt

    # Checkout is needed for using gh
    # Need to do this before writing any new files, as checkout deletes everything
    - name: Checkout the repo
      uses: actions/checkout@v3
      if:   ${{ steps.cache-restore.outputs.cache-hit }}

    - name: Save the date
      run:  |
        date
        date > date.txt

    - name: Clear the cache
      if:   ${{ steps.cache-restore.outputs.cache-hit }}
      run: |
        gh extension install actions/gh-actions-cache
        gh actions-cache delete ${{ env.key }} --confirm

    - name: Save the cache
      uses: actions/cache/save@v3
      # if: always()  # save cache even fails
      with:
        path: date.txt
        key:  ${{ env.key }}
