
on:
  - push
  - pull_request
  - workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  ghcup:
    runs-on: ubuntu-latest
    steps:

    # Install system requirements listed on https://www.haskell.org/ghcup/install/#system-requirements
    - run: |
        sudo apt install build-essential curl libffi-dev libffi7 libgmp-dev libgmp10 libncurses-dev libncurses5 libtinfo5

    - run: |
        ghcup install ghc 7.10.3 --set

    - run: |
        ghc -V
