jobs:
  pkg-config:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-10.15
          - macOS-11
          - macOS-12
    steps:
      - run: pkg-config --list-all
